In [ ]:
"""
In this file, we will take a look at broad trends and correlations. These include comparing overall 
energy production, consumption, and distribution with the market as a whole and specific sectors.
"""

In [13]:
# import functions and classes from our functions.py file we created during out data transformation process
from functions import energy_data_file_reference_function, folder_path, sheets_to_dataframes, table_transformer, transformed_energy_data

In [14]:
# create class with all our data
# folder_path to our data
folder_path = "C:/Users/danii/OneDrive/Desktop/Energy Data Files"

# run functions to get our data
energy_data_file_reference_function(folder_path)
transformed_energy_data()

In [21]:
# view all transformed DataFrames we can access from our class
class_directory = list(filter(lambda x: not x.startswith("_"), dir(transformed_energy_data)))
print(class_directory)

['biofuel_prod', 'biomass_consump', 'coal_consump', 'coal_expend', 'coal_prices', 'coal_prod', 'commer_consump', 'commer_consump_percap', 'commer_expend', 'commer_prices', 'crude_prod', 'elec_expend', 'elec_prices', 'ener_consump_per_realgdp', 'geother_consump', 'hydro_consump', 'indust_consump', 'indust_consump_percap', 'indust_expend', 'indust_prices', 'motogas_expend', 'motogas_expend_percap', 'motogas_prices', 'natgas_consump', 'natgas_expend', 'natgas_prices', 'natgas_prod', 'np', 'nuclear_consump', 'nuclear_prod', 'other_renew_prod', 'petro_consump', 'petro_expend', 'petro_prices', 'realgdp2', 'reduce', 'resid_consump', 'resid_consump_percap', 'resid_elec_sales', 'resid_elec_sales_percap', 'resid_expend', 'resid_prices', 'solar_consump', 'tot_consump', 'tot_ener_prod', 'tot_expend', 'tot_expend_percap', 'tot_expend_pergdp', 'tot_expend_prices', 'tot_prime_consump', 'tot_prime_prod', 'tot_renew_consump', 'tot_renew_prod', 'tot_ret_elec_sales', 'tot_ret_elec_sales_percap', 'tot_sec_consump', 'tot_sec_consump_percap', 'tot_sec_expend', 'tot_sec_prices', 'transp_consump', 'transp_consump_percap', 'transp_expend', 'transp_prices', 'wind_consump', 'wood_waste_prod', 'year']

In [23]:
# view total energy production
transformed_energy_data.tot_ener_prod

"Total energy production, billion Btu",Year,Alaska,Alabama,Arkansas,Arizona,California,Colorado,Connecticut,District of Columbia,Delaware,...,Tennessee,Texas,Utah,Virginia,Vermont,Washington,Wisconsin,West Virginia,Wyoming,US Total
0,1960,21554.0,474228.0,289299.0,36737.0,2631000.0,481892.0,17406.0,155.0,4982.0,...,287803.0,12058639.0,389409.0,824357.0,17339.0,431849.0,64968.0,3236932.0,1018033.0,42590504.0
1,1961,56144.0,474778.0,291209.0,35506.0,2619873.0,478635.0,17076.0,163.0,5101.0,...,283981.0,12208006.0,373419.0,887666.0,15369.0,458873.0,60619.0,3091375.0,1087707.0,43073574.0
2,1962,82748.0,484723.0,282213.0,35003.0,2692352.0,442430.0,15937.0,166.0,5134.0,...,301330.0,12357635.0,359952.0,864865.0,15682.0,480508.0,61695.0,3227721.0,1067807.0,44668026.0
3,1963,87933.0,469027.0,284502.0,36668.0,2844641.0,429188.0,16253.0,148.0,5356.0,...,280926.0,12693749.0,377875.0,890108.0,13995.0,517358.0,55114.0,3576720.0,1130426.0,46985037.0
4,1964,90198.0,541262.0,281323.0,36786.0,2832949.0,432566.0,16703.0,138.0,5510.0,...,292122.0,13123816.0,365533.0,920711.0,13500.0,558451.0,54980.0,3797124.0,1123168.0,48860983.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,2016,1435363.0,1118407.0,1127828.0,593930.0,2426284.0,3065494.0,207612.0,1107.0,3105.0,...,485787.0,17008753.0,923606.0,913066.0,35637.0,1031454.0,330423.0,3791823.0,7518440.0,84360739.0
57,2017,1454196.0,1230179.0,989005.0,621896.0,2542051.0,3246984.0,205458.0,1316.0,3269.0,...,515435.0,17721412.0,915007.0,925794.0,37792.0,1035233.0,325091.0,4317700.0,7794586.0,88208472.0
58,2018,1410604.0,1245875.0,888125.0,622052.0,2362317.0,3633905.0,214068.0,1603.0,3389.0,...,575228.0,20619040.0,893795.0,901990.0,41553.0,1039226.0,337996.0,4746299.0,7711992.0,95806874.0
59,2019,1370342.0,1250624.0,837386.0,563836.0,2420522.0,3927798.0,211902.0,2002.0,3611.0,...,569785.0,23634727.0,884243.0,882858.0,40997.0,871660.0,337188.0,5160593.0,7148285.0,101523760.0
60,2020,1348969.0,1205912.0,782360.0,481613.0,2190166.0,3775295.0,201489.0,2147.0,3571.0,...,591321.0,23329131.0,789072.0,821769.0,37481.0,969677.0,302978.0,5020189.0,5884410.0,95710873.0